remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Christian Gómez - Programador Web
description: Programador informático que presta servicios en Aldaia, Valencia.
